use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
ast
marpa
ncurses
terminfo
bnf
longname
aix
osf
hpux
uwin
txt
posix
baudrate
ospeed
tgetent
capabilitty
tputs
lexeme
parameterized
nethack
fildes
putp
setupterm
stdout
jddurand
jeandamiendurand
Jean
Durand
lib
MarpaX
Database
Terminfo
Grammar
CharacterClasses
Interface
Constants
Regexp
Actions
String
